export enum ApplicationsEnum {
  ADMIN = "ADMIN",
  SITE = "SITE",
  PORTAL_MEMBER = "PORTAL_MEMBER",
  CHURCH_MANAGER = "CHURCH_MANAGER",
  EVENTS_CONTROLLER = "EVENTS_CONTROLLER",
  EAD_STUDANT = "EAD_STUDANT",
  EAD_TEACHER = "EAD_TEACHER",
  EAD_ADMIN = "EAD_ADMIN",
}
